version: 2
jobs:
  build:
    docker:
      - image: gradle
    steps:
      - checkout
      - run: gradle clean
      - run: gradle fatJar
  deploy:
    docker:
      - image: busybox
    steps:
      - run: echo "Application has been deployed"
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - hold:
          type: approval
          requires: 
            - build
      - deploy:
          requires:
            - hold