version: 2
jobs:
  build:
    docker:
      - image: gradle
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8a:f6:28:26:07:00:75:08:e3:95:09:49:c8:62:11:d1"
      - checkout
      - run: gradle clean
      - run: gradle fatJar
      - run: 
          command: |
            git config user.name "Release Script"
            git config user.email "builds@understoryweather.com"
            touch b
            # commit and tag
            git add .
            git commit -m "release: bla"
            git tag "bla"
            git push --tags
workflows:
  version: 2
  workflow:
    jobs:
      - build
