version: 2
jobs:
  build:
    docker:
      - image: gradle
    steps:
      - checkout
      - run: gradle clean
      - run: gradle fatJar
  hold:
    type: approval
    requires: build
  deploy:
    requires:
      - hold
    docker:
      - image: gradle
      - run: echo "Application has been deployed"