workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      build:
        docker:
          - image: gradle
        steps:
          - checkout
          - run: gradle clean
          - run: gradle fatJar
      hold:
        type: approval
        requires: build
      deploy:
        requires:
          - hold
        docker:
          - image: busybox
        steps:
          - run: echo "Application has been deployed"