version: 2
jobs:
  build:
    docker:
      - image: gradle
    steps:
      - checkout
      - run: gradle clean
      - run: gradle fatJar
  hold:
    type: approval
    requires: build
    docker:
      - image: busybox
    steps:
      - run: echo "Received Approval for deployment"
  deploy:
    requires:
      - hold
    docker:
      - image: busybox
    steps:
      - run: echo "Application has been deployed"
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - hold
    - deploy