version: 2
jobs:
  build:
    docker:
      - image: gradle
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8a:f6:28:26:07:00:75:08:e3:95:09:49:c8:62:11:d1"
      - checkout
      - run: gradle clean
      - run: gradle fatJar
      - run: |
        git config user.name "Release Script"
        git config user.email "builds@understoryweather.com"
        git touch a
        # commit and tag
        git add a
        git commit -m "release: bla"
        git tag "bla"
        git push
workflows:
  version: 2
  workflow:
    jobs:
      - build
