version: 2
jobs:
  build:
    docker:
      - image: gradle
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8a:f6:28:26:07:00:75:08:e3:95:09:49:c8:62:11:d1"
      - checkout
      - run: gradle clean
      - run: gradle fatJar
workflows:
  version: 2
  workflow:
    jobs:
      - build
