version: 2
jobs:
  build:
    docker:
      - image: gradle
    steps:
      - checkout
      - run: gradle clean
      - run: gradle fatJar
workflows:
  version: 2
  workflow:
    jobs:
      - build
